# Generated by Django 5.1.7 on 2026-10-08 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('registrations', models.PositiveIntegerField(default=0)),
                ('wrong_registrations', models.PositiveIntegerField(default=0)),
                ('precision', models.FloatField(default=0.0)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='inspection.inspectionexercise')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionFragment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('defect_type', models.CharField(blank=True, choices=[('ambiguity', 'Ambigüedad'), ('incomplete', 'Omisión / Incompletitud'), ('inconsistency', 'Inconsistencia / Contradicción'), ('unverifiable', 'No verificable'), ('redundancy', 'Redundancia'), ('design', 'Imposición de diseño')], max_length=20)),
                ('explanation', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='inspection.inspectionexercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_type', models.CharField(choices=[('ambiguity', 'Ambigüedad'), ('incomplete', 'Omisión / Incompletitud'), ('inconsistency', 'Inconsistencia / Contradicción'), ('unverifiable', 'No verificable'), ('redundancy', 'Redundancia'), ('design', 'Imposición de diseño')], max_length=20)),
                ('is_correct', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspection.inspectionattempt')),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.inspectionfragment')),
            ],
            options={
                'ordering': ['fragment__order'],
                'unique_together': {('attempt', 'fragment')},
            },
        ),
    ]
