# Generated by Django 5.1.7 on 2026-10-08 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_code', models.CharField(max_length=50)),
                ('version_number', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('client_name', models.CharField(max_length=120)),
                ('client_role', models.CharField(max_length=160)),
                ('client_greeting', models.TextField()),
            ],
            options={
                'db_table': 'scenarios_version',
                'ordering': ['scenario_code'],
                'unique_together': {('scenario_code', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=80)),
                ('text', models.CharField(max_length=300)),
                ('answer_segments', models.JSONField()),
                ('is_key', models.BooleanField(default=True, help_text='Tema clave para la cobertura de la entrevista')),
                ('order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.scenarioversion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('interviewing', 'Entrevista en curso'), ('classifying', 'Clasificación de requisitos')], default='interviewing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('interview_finished_at', models.DateTimeField(blank=True, null=True)),
                ('premature_finish', models.BooleanField(default=False)),
                ('interview_score', models.IntegerField(default=0)),
                ('classification_score', models.IntegerField(default=0)),
                ('classification_precision', models.FloatField(default=0.0)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='interviews.scenarioversion')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20)),
                ('statement_text', models.TextField()),
                ('expected_type', models.CharField(choices=[('RF', 'Requisito Funcional'), ('RNF', 'Requisito No Funcional')], max_length=3)),
                ('feedback_explanation', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='interviews.interviewquestion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='interviews.scenarioversion')),
            ],
            options={
                'db_table': 'master_requirements',
                'constraints': [models.CheckConstraint(condition=models.Q(('expected_type__in', ['RF', 'RNF'])), name='master_req_type_valid')],
                'unique_together': {('version', 'key')},
            },
        ),
        migrations.CreateModel(
            name='InterviewLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.interviewquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='interviews.studentattempt')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
