# Generated by Django 5.1.7 on 2026-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ['round_number', 'order']},
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='is_key',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='quality',
            field=models.CharField(choices=[('high', 'Muy útil'), ('medium', 'Algo útil'), ('low', 'No aporta')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='rationale',
            field=models.TextField(blank=True, help_text='Por qué la pregunta aporta (o no) a la entrevista'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='round_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
