# Generated by Django 5.1.7 on 2026-10-08 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_category', models.CharField(choices=[('RF', 'Requisito Funcional'), ('RNF', 'Requisito No Funcional')], max_length=3)),
                ('is_correct', models.BooleanField()),
                ('times_changed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='interviews.studentattempt')),
                ('master_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.masterrequirement')),
            ],
            options={
                'db_table': 'student_classifications',
                'ordering': ['updated_at'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'master_requirement'), name='unique_classification_per_attempt'), models.CheckConstraint(condition=models.Q(('selected_category__in', ['RF', 'RNF'])), name='classification_type_valid')],
            },
        ),
    ]
