# Generated by Django 5.1.7 on 2026-10-08 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseSpecification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('system_name', models.CharField(default='Sistema', max_length=200)),
                ('actors', models.JSONField()),
                ('preconditions', models.TextField()),
                ('main_flow', models.JSONField()),
                ('alternate_flows', models.JSONField(default=list)),
                ('postconditions', models.TextField()),
                ('relations', models.JSONField(default=list)),
                ('plantuml_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, help_text='Entrevista que sirve de guía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_cases', to='interviews.studentattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usecase_specifications',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('svg', models.TextField()),
                ('engine', models.CharField(max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagram', to='modeling.usecasespecification')),
            ],
        ),
    ]
